# Generated by Django 4.0 on 2022-01-05 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Департаменти')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Департаменти',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Керівництво',
                'verbose_name_plural': 'Керівництво',
            },
        ),
        migrations.CreateModel(
            name='PersonnelStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Персонал>> структура',
                'verbose_name_plural': '<<Персонал>> Структура',
            },
        ),
        migrations.CreateModel(
            name='PersonnelArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Персонал>> стаття',
                'verbose_name_plural': '<<Персонал>> статті',
            },
        ),
        migrations.CreateModel(
            name='OperationsStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Операційний>> структура',
                'verbose_name_plural': '<<Операційний>> структура',
            },
        ),
        migrations.CreateModel(
            name='OperationsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Операційний>> стаття',
                'verbose_name_plural': '<<Операційний>> статті',
            },
        ),
        migrations.CreateModel(
            name='MarketingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Маркетинг>> структура ',
                'verbose_name_plural': '<<Маркетинг>> структура',
            },
        ),
        migrations.CreateModel(
            name='MarketingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Маркетинг>> стаття',
                'verbose_name_plural': '<<Маркетинг>> статті',
            },
        ),
        migrations.CreateModel(
            name='ItStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<IT>> структура',
                'verbose_name_plural': '<<IT>> структура',
            },
        ),
        migrations.CreateModel(
            name='ItArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<IT>> стаття',
                'verbose_name_plural': '<<IT>> статті',
            },
        ),
        migrations.CreateModel(
            name='FinancialStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Фінансовий>> структура',
                'verbose_name_plural': '<<Фінансовий>> структура',
            },
        ),
        migrations.CreateModel(
            name='FinancialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Фінансовий>> стаття',
                'verbose_name_plural': '<<Фінансовий>> статті',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Розвиток>> структура',
                'verbose_name_plural': '<<Розвиток>> структура',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Розвиток>> стаття',
                'verbose_name_plural': '<<Розвиток>> статті',
            },
        ),
        migrations.CreateModel(
            name='CommercialStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Комерційний>> структура',
                'verbose_name_plural': '<<Комерційний>> структура',
            },
        ),
        migrations.CreateModel(
            name='CommercialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Комерційний>> стаття',
                'verbose_name_plural': '<<Комерційний>> статті',
            },
        ),
        migrations.CreateModel(
            name='AccountingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Прізвище Ім'я По батькові", max_length=150, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='workers/', verbose_name='Фото')),
                ('phone', models.CharField(help_text='Формат: 380xxxxxxxxx', max_length=12, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Бухгалтерія>> структура',
                'verbose_name_plural': '<<Бухгалтерія>> структура',
            },
        ),
        migrations.CreateModel(
            name='AccountingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Бухгалтерія>> стаття',
                'verbose_name_plural': '<<Бухгалтерія>> статті',
            },
        ),
    ]
