# Generated by Django 4.0 on 2022-01-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Бухгалтерія категорія')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Бухгалтерія категорія',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItCategoryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='IT категорія')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'IT категорія',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='accountingstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Бухгалтерія>> структура', 'verbose_name_plural': '<<Бухгалтерія>> структура'},
        ),
        migrations.AlterModelOptions(
            name='commercialstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Комерційний>> структура', 'verbose_name_plural': '<<Комерційний>> структура'},
        ),
        migrations.AlterModelOptions(
            name='developmentstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Розвиток>> структура', 'verbose_name_plural': '<<Розвиток>> структура'},
        ),
        migrations.AlterModelOptions(
            name='financialstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Фінансовий>> структура', 'verbose_name_plural': '<<Фінансовий>> структура'},
        ),
        migrations.AlterModelOptions(
            name='itstructure',
            options={'ordering': ['id'], 'verbose_name': '<<IT>> структура', 'verbose_name_plural': '<<IT>> структура'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['id'], 'verbose_name': 'Керівництво', 'verbose_name_plural': 'Керівництво'},
        ),
        migrations.AlterModelOptions(
            name='marketingstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Маркетинг>> структура ', 'verbose_name_plural': '<<Маркетинг>> структура'},
        ),
        migrations.AlterModelOptions(
            name='operationsstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Операційний>> структура', 'verbose_name_plural': '<<Операційний>> структура'},
        ),
        migrations.AlterModelOptions(
            name='personnelstructure',
            options={'ordering': ['id'], 'verbose_name': '<<Персонал>> структура', 'verbose_name_plural': '<<Персонал>> Структура'},
        ),
        migrations.AddField(
            model_name='accountingarticle',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.accountingcategoryarticle', verbose_name='Бухгалтерія категорія'),
        ),
        migrations.AddField(
            model_name='itarticle',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.itcategoryarticle', verbose_name='IT категорія'),
        ),
    ]
