# Generated by Django 4.0 on 2022-01-18 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_accountingcategoryarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingcategoryarticle',
            options={'ordering': ['id'], 'verbose_name_plural': '<<Бухгалтерія>> категорії'},
        ),
        migrations.AlterModelOptions(
            name='itcategoryarticle',
            options={'ordering': ['id'], 'verbose_name_plural': '<<IT>> категорії'},
        ),
        migrations.CreateModel(
            name='SecurityArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_create', models.DateField(default=datetime.date.today, verbose_name='Дата створення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': '<<Безпека>> стаття',
                'verbose_name_plural': '<<Безпека>> статті',
            },
        ),
    ]
